In [1]:
from timeit import timeit
import numpy as np

In [3]:
%timeit np.arange(10e6)

12.9 ms ± 485 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

# Internals

In [11]:
a.__array_interface__

{'data': (94457996287616, False),
 'strides': None,
 'descr': [('', '<f8')],
 'typestr': '<f8',
 'shape': (5,),
 'version': 3}

In [13]:
a.itemsize # size of one element

8

In [14]:
# a more complex array
b = np.arange(12).reshape(4,3).astype(np.int8)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int8)

In [15]:
b.__array_interface__

{'data': (94457996731520, False),
 'strides': None,
 'descr': [('', '|i1')],
 'typestr': '|i1',
 'shape': (4, 3),
 'version': 3}

In [31]:
# computes strides
stride_next_col = b.itemsize
stride_next_row = b.itemsize * b.shape[1]
np.allclose([stride_next_row,stride_next_col], b.strides)

# to move to the next row, we need to traverse the current row first (all np array are 1-dim in memory)

True

In [32]:
b.strides

(3, 1)

In [60]:
# pointer to the end point of an array
np.byte_bounds(b) # compare it with data in __array_interface__

(140322661516160, 140322669516160)

# Views vs Copies

In [49]:
# simple indexing will return a copy. To check whether an array is a view or a copy, we can check the base attirbute

a = np.array([1 , 2, 3, 4])
print(c.base is None)
b = c[:3]
print(b.base)
# reshaping will not create a copy, 
c = a.reshape(2, 2)
print(c.base)
print(c.strides)

# nested view, they will all get the same base
d = c.reshape(4,1)
print(d.base)
print(d.strides)

# Copies of course can be expensive

False
[1 2 3 4]
[1 2 3 4]
(16, 8)
[1 2 3 4]
(8, 8)


In [58]:
# arithmetic operations
a = np.ones(10**6)
b = np.ones(10**6)

In [57]:
# multiplication
%timeit 3*a
%timeit np.multiply(a, 3, out=a)

492 µs ± 15.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
115 µs ± 7.41 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Functions to create standard arrays

In [21]:
# It is faster to create a costant array with np.full, the second method will first create an array of 1 and after
#it will create a copy
%timeit np.full((20000,20000), 7) # a costant array

%timeit np.ones((20000,20000)) * 7

347 ms ± 4.29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
542 ms ± 2.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
# same speed in this case
%timeit np.full((20000,20000), 1) # a costant array

%timeit np.ones((20000,20000))

344 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
344 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
# diagonal matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])